### ISSUE TITLE
Sample of how to use or config this library

### ISSUE THREAD

**Issue by e2tox** [alexeibs/ts-format-imports#1]
Hello,

I have checked your repo. It's really cool. I want to know how to use this package and config in another typescript project. Just one or two lines of code will be very helpful.

**Comment by e2tox** [comment]
I will check the spec first.

**Comment by alexeibs** [comment]
It's not quite working yet :) After 'npm install' you can run this command:
`node_modules/.bin/ts-format-imports input_filename.ts`
It will produce `input_filename.ts.organized` with import declarations sorted. It also removes duplicates. Sorting is not configurable for now.
